add a checkpoint in asyncio process_signal_queue
agronholm/anyio pull request #202
Opened 2021-02-21 13:12 UTC by graingert

2021-02-21 13:31 UTC, graingert commented on tests/test_signals.py
> +                await tg.cancel_scope.cancel()
```suggestion
    async with open_signal_receiver(signal.SIGUSR1) as sigiter:
        async with create_task_group() as tg:
            await tg.spawn(consume, sigiter)
            await tg.cancel_scope.cancel()
```

2021-02-21 17:08 UTC, agronholm requested changes
I'd like some minor changes, but overall looks fine.

2021-02-21 17:08 UTC, agronholm commented on tests/test_signals.py
> +async def test_task_group_cancellation_open() -> None:
Why bother with annotations in the tests? No other tests have any.

2021-02-21 17:08 UTC, agronholm commented on tests/test_signals.py
> +            assert False
I'd prefer all the `assert False` statements be turned into proper `pytest.fail()` calls with an explanation message.

2021-02-21 17:08 UTC, agronholm commented on tests/test_signals.py
> +    async def consume(sigiter: AsyncIterator[object]) -> None:
Annotations here, as above.

2021-02-21 17:08 UTC, agronholm commented on tests/test_signals.py
> +@pytest.mark.skipif(sys.platform == 'win32', reason='Signal delivery cannot be tested on Windows')
These could be move to the `pytestmark` collection since there are more than one now.

2021-02-21 17:08 UTC, agronholm commented on tests/test_signals.py
> +            assert False
Also here, `pytest.fail(...)`.

2021-02-22 06:42 UTC, agronholm commented
I looked at this with fresh eyes now and I'm not sure I should merge this at all. If you look at the sync-event-set branch, you'll see that signal waiting is done quite differently over there, and your other PR makes checkpoints there more or less pointless.

2021-02-22 09:17 UTC, graingert commented
closing in favour of https://github.com/agronholm/anyio/pull/203

2021-02-22 09:17 UTC, closed without merging