Support setting subprocess std* arguments to file objects or None
agronholm/anyio pull request #421
Opened 2022-02-21 23:29 UTC by jwodder

Closes #419.

So it turns out that there's nothing currently in the code to stop users from pasing file objects or `None` to `open_process()`, so all this PR needed to do was update the type annotations & docs and add tests.

Regarding the type annotations for the `std*` arguments, [typeshed says][1] that asyncio takes `Union[int, IO[Any], None]`, while [trio-typing says][2] that trio takes `int`, `None`, or anything with a `fileno()` method.  As [`IO` comes with a `fileno()`][3], that makes it the stricter choice and thus the one supported by both backends.

As far as I'm aware, the only thing really missing from this PR is a test of `stdin=None`, but I'm not sure how to go about writing that.  Thoughts?

[1]: https://github.com/python/typeshed/blob/3afc0b1adeac3d74674c32605f112bdbfe24b530/stdlib/asyncio/subprocess.pyi
[2]: https://github.com/python-trio/trio-typing/blob/34fa626eaa971c50988eb54f71ddbe4384535b4a/trio-stubs/__init__.pyi
[3]: https://github.com/python/cpython/blob/c596ecbf821843de0e044f0d4da34c6b49a06907/Lib/typing.py#L2503

2022-05-08 10:33 UTC, agronholm requested changes
Just a few code style nits, otherwise LGTM.

2022-05-08 10:33 UTC, agronholm commented on tests/test_subprocesses.py
> +    assert stdoutfile.read_text() == "stdin says 'Hello, process!' and stdout says YES!\n"
Add a blank line after a control block if the code continues on the same level.
```suggestion

    assert stdoutfile.read_text() == "stdin says 'Hello, process!' and stdout says YES!\n"
```

2022-05-08 10:33 UTC, agronholm commented on src/anyio/_core/_subprocesses.py
> +        :data:`subprocess.STDOUT`, a file-like object, or `None`
Switched None to use two backticks as everywhere else in the codebase.
```suggestion
    :param stdin: one of :data:`subprocess.PIPE`, :data:`subprocess.DEVNULL`, a
        file-like object, or ``None``
    :param stdout: one of :data:`subprocess.PIPE`, :data:`subprocess.DEVNULL`,
        a file-like object, or ``None``
    :param stderr: one of :data:`subprocess.PIPE`, :data:`subprocess.DEVNULL`,
        :data:`subprocess.STDOUT`, a file-like object, or ``None``
```

2022-05-08 10:41 UTC, agronholm commented
Needs a few fixes still; I'm on it.

2022-05-08 10:47 UTC, agronholm approved these changes

2022-05-08 11:00 UTC, agronholm commented
Ok, seems to work now. The py3.11 failure is due to coverage incompatibility.

2022-05-08 11:01 UTC, merged

2022-05-08 11:01 UTC, agronholm commented
Thanks!

2025-01-10 23:18 UTC, jmehnle commented
@agronholm, for lack of a better forum (particularly, app.gitter.im seems to be down right now), is there a good reason `anyio.run_process()` can't accept a `stdin` argument with a file handle (such as `sys.stdin`)? Both [`subprocess.run()`](https://docs.python.org/3/library/subprocess.html#subprocess.run) and [`trio.run_process()`](https://trio.readthedocs.io/en/stable/reference-io.html#trio.run_process) support this, yet `anyio.run_process()` only accepts a static `input` string or bytes. (Why is this useful? I'm writing a shell wrapper that spawns a user-provided subprocess, which may or may not expect user interaction on `stdin`. This works with Trio but not with AnyIO.)

2025-01-10 23:20 UTC, agronholm commented
Does it work with asyncio's subprocess API too? If so, I could accept a PR to allow that.

2025-01-11 00:38 UTC, jmehnle commented
It seems to work on both `asyncio` and `trio`: https://github.com/agronholm/anyio/pull/859