Add `__del__` method to `MemoryObject*Stream` with calling a close
agronholm/anyio pull request #663
Opened 2024-01-05 14:44 UTC by heckad

2024-01-05 22:52 UTC, agronholm commented
The best one can safely do in `__del__()` is to raise a `ResourceWarning`. Closing is not safe, as the destructor could be called in any thread.

2024-02-19 08:17 UTC, agronholm commented
Do you intend to replace the close() into raising a ResourceWarning? If not, then I'll close this.

2024-02-20 07:07 UTC, agronholm requested changes
Aside from the suggested changes, this needs tests, and a note in the changelog. Note that those tests will probably need to call `gc.collect()` to get the desired result on PyPy.

2024-03-09 12:49 UTC, agronholm commented on src/anyio/_backends/_asyncio.py
> +            send_stream.close()
It would be better to set up `.close()` as a "done callback" of the runner task, in `_call_in_runner_task()`.

2024-03-16 20:11 UTC, agronholm requested changes
Much better, but please also drop the storing of tracebacks. Storing tracebacks is problematic from the memory management standpoint, and although I can see the objective, I think the `tracemalloc` system can be used to retrieve the same information. Nevertheless, I don't want the tracebacks stored.

2024-03-16 23:42 UTC, heckad commented
Unfortunately it doesn't work.
```python
import tracemalloc
import warnings


class Foo:
    pass


def main():
    tracemalloc.start(65535)

    foo = Foo()

    warnings.warn("Foo", ResourceWarning, source=foo)

    bar = object()

    warnings.warn("Bar", ResourceWarning, source=bar)


if __name__ == "__main__":
    main()
```
Outputs
```
D:\projects\python\test\test16.py:14: ResourceWarning: Foo
  warnings.warn("Foo", ResourceWarning, source=foo)
D:\projects\python\test\test16.py:18: ResourceWarning: Bar
  warnings.warn("Bar", ResourceWarning, source=bar)
Object allocated at (most recent call last):
  File "D:\projects\python\test\test16.py", lineno 22
    main()
  File "D:\projects\python\test\test16.py", lineno 16
    bar = object()
```
Test on `Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)] on win32`
The same problem with `MemoryObject*Stream`. 
Additionally, the maximum number of stack traces is 65535. This means that if our streams live long, we won't know where we created them. I can place stacktraces inside 
```python
if sys.flags.dev_mode:
    ....
```
What do you think?

2024-03-19 22:47 UTC, agronholm commented
I think I would feel a lot more at ease if the tracebacks were at least formatted, so as to remove any circular references. And it would still have to be hidden behind that dev mode flag.

Is any other project storing tracebacks like this? I'd like to check what others are doing and if there are alternatives.

2024-03-20 00:32 UTC, heckad commented
> I think I would feel a lot more at ease if the tracebacks were at least formatted, so as to remove any circular references.

Sorry, could you clarify what cyclic dependencies you are talking about? The function `traceback.extract_stack` returns StackSummary type which contains info about the stack, not the stack like in `Exception.__traceback__`
![image](https://github.com/agronholm/anyio/assets/45011689/2b7d9c81-b61a-468e-9e61-3cb6aeaf5322)

> Is any other project storing tracebacks like this? I'd like to check what others are doing and if there are alternatives.

For example [`aiohttp`](https://github.com/aio-libs/aiohttp/blob/58a9190ed092e5748e80e16082592b886d105975/aiohttp/client.py#L263C1-L268C42)

2024-03-20 09:13 UTC, smurfix commented
While the `StackSummary` contains a `locals` attribute, it defaults to being empty unless you specifically tell the `TracebackException` that `capture_locals=True`.

That being said, building and storing a stack traceback in every stream is prohibitively expensive even if there are no reference cycles. Don't do that.

If/when it's really necessary to save the entire call chain, well, people should be perfectly capable of monkeypatching `create_m_o_stream`.

2024-03-20 09:18 UTC, agronholm commented
> While the `StackSummary` contains a `locals` attribute, it defaults to being empty unless you specifically tell the `TracebackException` that `capture_locals=True`.
> 
> That being said, building and storing a stack traceback in every stream is prohibitively expensive even if there are no reference cycles. Don't do that.
> 
> If/when it's really necessary to save the entire call chain, well, people should be perfectly capable of monkeypatching `create_m_o_stream`.

OP's idea was to only do that when the dev mode is enabled, though.

2024-03-20 10:02 UTC, agronholm commented
If indeed this is hidden behind dev mode, then I am warming up to the idea.

2024-03-20 10:28 UTC, agronholm commented
Regarding tracemalloc, why are you saying it's not working? This is what I see:
```
bug.py:14: ResourceWarning: Foo
  warnings.warn("Foo", ResourceWarning, source=foo)
Object allocated at (most recent call last):
  File "bug.py", lineno 22
    main()
  File "bug.py", lineno 12
    foo = Foo()
bug.py:18: ResourceWarning: Bar
  warnings.warn("Bar", ResourceWarning, source=bar)
Object allocated at (most recent call last):
  File "bug.py", lineno 22
    main()
  File "bug.py", lineno 16
    bar = object()
```
Seems to work fine?

2024-04-04 20:52 UTC, agronholm commented
@heckad I'd like to get this into the new release. We just need to resolve the issue with stack summaries. You haven't replied to my latest comment. If the code is going to be merged with stack summaries, then that needs to be opt-in using the `dev_mode` flag.

2024-04-09 10:05 UTC, agronholm requested changes
Almost perfect now, just two small changes I want.

2024-04-09 10:05 UTC, agronholm commented on src/anyio/streams/memory.py
> +        return sys.flags.dev_mode
I'd rather not add a new public method for this.
```suggestion
        if sys.flags.dev_mode:
            self._source_traceback = traceback.extract_stack(sys._getframe(1))
```

2024-04-09 10:05 UTC, agronholm commented on src/anyio/streams/memory.py
> +        return sys.flags.dev_mode
As above.
```suggestion
        if sys.flags.dev_mode:
            self._source_traceback = traceback.extract_stack(sys._getframe(1))
```

2024-04-10 08:12 UTC, heckad commented
> Why'd you still keep that extra method?

For the ability to override detecting dev mode logic in child classes.

2024-04-10 08:13 UTC, agronholm commented
> > Why'd you still keep that extra method?
> 
> For the ability to override detecting dev mode logic in child classes.

Why not just look at `sys.flags.dev_mode` then?

2024-04-10 08:14 UTC, agronholm commented
At any rate, just using `sys.flags.dev_mode` is as far as I'm willing to take this. Please remove the method and I'll merge.

2024-04-10 08:25 UTC, closed without merging

2024-04-10 08:26 UTC, agronholm commented
Why'd you close this?